# Generated by Django 4.0.3 on 2022-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crafts', '0002_delete_logaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=10)),
                ('profile_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterProfile',
        ),
    ]
